'use client';
import { useEffect, useMemo, useState, useDeferredValue } from 'react';
import { ArrowRight, ArrowUpRight, Search, MapPin, SlidersHorizontal, X, Download, Mountain, ChevronLeft, ChevronRight, CalendarDays, ExternalLink } from 'lucide-react';
import { flushSync } from 'react-dom';
import { registerArchiveTool } from '@/lib/webmcp';
import { Header } from '@/components/header';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Pagination, PaginationContent, PaginationItem } from '@/components/ui/pagination';
import { Empty, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { Skeleton } from '@/components/ui/skeleton';
import type { Incident } from '@/lib/types';
import { createSearch, defaults, label, formatDate, sourceLinks, type Filters } from '@/lib/search';
function Picker({title,value,options,onChange}:{title:string;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void}) {return <div className="picker"><label>{title}</label><Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger aria-label={title}><SelectValue>{options.find(o=>o.value===value)?.label || value}</SelectValue></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
export default function Home(){
 const [records,setRecords]=useState<Incident[]>([]),[status,setStatus]=useState('loading');
 const [filters,setFilters]=useState<Filters>(defaults),[page,setPage]=useState(1),[ready,setReady]=useState(false);
 const [selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<Incident|null>(null),[detailError,setDetailError]=useState(false);
 const deferred=useDeferredValue(filters),search=useMemo(()=>createSearch(records),[records]);
 const results=useMemo(()=>search(deferred),[search,deferred]);
 const years=useMemo(()=>[...new Set(records.map(r=>r.date.slice(0,4)))].sort().reverse(),[records]);
 const types=useMemo(()=>[...new Set(records.map(r=>r.incident_type).filter(Boolean) as string[])].sort(),[records]);
 const countByYear=useMemo(()=>years.slice().reverse().map(y=>({year:y,count:records.filter(r=>r.date.startsWith(y)).length})),[years,records]);
 const maxCount=Math.max(1,...countByYear.map(y=>y.count));
 function update(key:keyof Filters,value:string){setFilters(f=>({...f,[key]:value,...(key==='q'?{sort:value.trim()?'relevance':'newest'}:{})}));setPage(1)}
 function clear(){setFilters(defaults);setPage(1)}
 useEffect(()=>{const ctrl=new AbortController();fetch('/data/incidents.json',{signal:ctrl.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(r=>{setRecords(r as Incident[]);setStatus('loaded')}).catch(e=>{if(e.name!=='AbortError')setStatus('error')});const params=new URLSearchParams(location.search);setFilters({...defaults,...Object.fromEntries(Object.keys(defaults).filter(k=>params.has(k)).map(k=>[k,params.get(k)!]))});const id=params.get('incident');if(id&&/^(legacy-\d{6}|[0-9a-f-]{36})$/.test(id))setSelected(id);setReady(true);return()=>ctrl.abort()},[]);
 useEffect(()=>{if(!ready)return;const p=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>{if(v!==defaults[k as keyof Filters])p.set(k,v)});if(selected)p.set('incident',selected);history.replaceState(null,'',p.size?'/?'+p.toString():'/')},[filters,selected,ready]);
 useEffect(()=>{setDetail(null);setDetailError(false);if(!selected)return;const ctrl=new AbortController();fetch('/data/incidents/'+encodeURIComponent(selected)+'.json',{signal:ctrl.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(r=>setDetail(r as Incident)).catch(e=>{if(e.name!=='AbortError')setDetailError(true)});return()=>ctrl.abort()},[selected]);
 useEffect(()=>{if(status!=='loaded')return;const ctx=(document as unknown as {modelContext?:Parameters<typeof registerArchiveTool>[0]}).modelContext;return registerArchiveTool(ctx,search,f=>flushSync(()=>{setFilters(f);setPage(1)}))},[search,status]);
 const active=filters.q||filters.location||filters.year!=='all'||filters.type!=='all';
 const pages=Math.max(1,Math.ceil(results.length/20)),safePage=Math.min(page,pages);
 return <><Header/><main id="main-content" className="archive"><section className="intro"><div><p className="eyebrow"><span/> PUBLIC RECORD • COLORADO BACKCOUNTRY</p><h1>Every rescue has a story.</h1><p className="intro-copy">Explore search and rescue incidents across Colorado.<br className="desktop-break"/> Find the places, circumstances, and source reports behind the record.</p></div><div className="archive-stat"><strong>{status==='loaded'?records.length.toLocaleString():'—'}</strong><span>INCIDENTS IN THE ARCHIVE</span><small>{years.length?`${years.at(-1)} — ${years[0]}`:'Loading archive'}</small></div></section>
 <div className="workspace"><aside className="filters"><div className="filter-title"><SlidersHorizontal size={17}/><h2>Refine the archive</h2></div><label className="field-label" htmlFor="location">Location</label><div className="input-wrap"><MapPin size={17}/><input id="location" value={filters.location} onChange={e=>update('location',e.target.value)} placeholder="Peak, trail, or county"/></div><p className="field-hint">Search places and county names.</p><Picker title="Year" value={filters.year} onChange={v=>update('year',v)} options={[{value:'all',label:'All years'},...years.map(y=>({value:y,label:y}))]}/><Picker title="Incident type" value={filters.type} onChange={v=>update('type',v)} options={[{value:'all',label:'All incident types'},...types.map(t=>({value:t,label:label(t)}))]}/>{active&&<button className="clear-button" onClick={clear}><X size={14}/> Clear all filters</button>}
 <div className="coverage"><p className="eyebrow">THE RECORD OVER TIME</p><div className="histogram" aria-label="Recorded incidents by year">{countByYear.map(y=><button key={y.year} title={`${y.year}: ${y.count} incidents`} aria-label={`Filter to ${y.year}, ${y.count} incidents`} className={filters.year===y.year?'chosen':''} onClick={()=>update('year',filters.year===y.year?'all':y.year)} style={{height:`${Math.max(4,y.count/maxCount*78)}px`}}/>)}</div><div className="axis"><span>{years.at(-1)}</span><span>{years[0]}</span></div><p>Counts reflect this collection, not all rescues. Coverage varies by year and agency.</p></div><a className="download" href="/data/colorado-sar.db" download><Download size={17}/><span>Download SQLite<small>Full archive · open format</small></span><ArrowUpRight size={16}/></a></aside>
 <section className="results" aria-label="Incident search"><div className="searchbar"><Search size={21}/><input aria-label="Search incident titles" placeholder="Search incident titles…" value={filters.q} onChange={e=>update('q',e.target.value)}/>{filters.q&&<button aria-label="Clear title search" onClick={()=>update('q','')}><X size={17}/></button>}<span className="fuzzy-label">FUZZY SEARCH</span></div><div className="results-toolbar"><p aria-live="polite">{status==='loaded'?<><b>{results.length.toLocaleString()}</b> {active?'matching':'recorded'} incidents</>:status==='error'?'Archive unavailable':'Loading incidents…'}</p><Picker title="Sort" value={filters.sort} onChange={v=>update('sort',v)} options={[{value:'newest',label:'Newest first'},{value:'oldest',label:'Oldest first'},...(filters.q?[{value:'relevance',label:'Best match'}]:[])]}/></div>
 {status==='error'?<Empty><EmptyTitle>Couldn’t load the archive</EmptyTitle><EmptyDescription>Check your connection and try again.</EmptyDescription><button className="action" onClick={()=>location.reload()}>Try again</button></Empty>:status==='loading'?<div className="loading-list">{[1,2,3,4].map(n=><Skeleton key={n} className="h-36 w-full"/>)}</div>:results.length===0?<Empty className="empty-state"><Mountain size={36}/><EmptyTitle>No incidents found</EmptyTitle><EmptyDescription>Try a broader place name, a shorter title search, or fewer filters.</EmptyDescription><button className="action" onClick={clear}>Reset filters</button></Empty>:<div className="incident-list">{results.slice((safePage-1)*20,safePage*20).map(r=><article key={r.id} className="incident"><div className="incident-date"><span>{formatDate(r.date).split(',')[0]}</span><small>{r.date.slice(0,4)}</small></div><div className="incident-main"><div className="incident-tags"><span className={'type-tag '+(r.incident_type==='avalanche'?'amber':'')}>{label(r.incident_type)}</span><span>{r.county||'County not recorded'}</span></div><button className="incident-title" onClick={()=>setSelected(r.id)}>{r.summary}</button><div className="incident-location"><MapPin size={14}/><span>{r.location||r.place||'Location not recorded'}</span></div></div><button className="open-incident" aria-label={`Read incident from ${r.date}`} onClick={()=>setSelected(r.id)}><ArrowRight size={20}/></button></article>)}</div>}
 {status==='loaded'&&results.length>0&&<Pagination className="pager"><PaginationContent><PaginationItem><button disabled={safePage===1} onClick={()=>setPage(safePage-1)}><ChevronLeft size={16}/> Previous</button></PaginationItem><PaginationItem><span>Page {safePage} of {pages}</span></PaginationItem><PaginationItem><button disabled={safePage===pages} onClick={()=>setPage(safePage+1)}>Next <ChevronRight size={16}/></button></PaginationItem></PaginationContent></Pagination>}
 </section></div><footer className="site-footer"><span>Colorado SAR Archive</span><p>An independent historical collection. For an emergency, call 911.</p><a href="/faq/">About the data <ArrowUpRight size={14}/></a></footer></main>
 <Sheet open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><SheetContent className="incident-sheet"><SheetHeader><p className="eyebrow">INCIDENT RECORD</p><SheetTitle>{detail?formatDate(detail.date):'Incident details'}</SheetTitle><SheetDescription>{detail?`${detail.county||'County not recorded'} · ${label(detail.incident_type)}`:'Source report and incident context'}</SheetDescription></SheetHeader>{detail?<div className="detail-body"><h2>{detail.summary}</h2><dl className="detail-grid">{[['Location',detail.location],['County',detail.county],['Incident type',label(detail.incident_type)],['Recorded outcome',label(detail.outcome)],['People involved',detail.victims],['Responding agency',detail.responding_agency],['Place',detail.place],['Peak',detail.peak],['Setting',detail.setting]].map(([k,v])=><div key={k as string}><dt>{k}</dt><dd>{v??'Not recorded'}</dd></div>)}</dl><section><h3>Notes & context</h3><p>{detail.notes||'No additional notes recorded.'}</p><p className="data-note">Outcomes and details may be incomplete or inferred. Check the original source and notes before drawing conclusions.</p></section><section><h3>Original sources</h3>{sourceLinks(detail.source_urls).length?sourceLinks(detail.source_urls).map((url,i)=><a className="source-link" key={i} href={url} target="_blank" rel="noopener noreferrer"><span>{new URL(url).hostname}<small>Source {i+1}</small></span><ExternalLink size={16}/></a>):<p>No source link recorded.</p>}</section>{detail.wx_source&&<section><h3>Historical weather context</h3><div className="weather"><span><b>{detail.wx_high_f??'—'}°F</b>High</span><span><b>{detail.wx_low_f??'—'}°F</b>Low</span><span><b>{detail.wx_gust_max_mph??'—'} mph</b>Max gust</span></div><p className="data-note">{detail.wx_source}. {detail.wx_note} Weather coordinates are contextual estimates, not verified incident locations.</p></section>}<div className="record-id">Record {detail.id}{detail.legacy_id?` · Original ID ${detail.legacy_id}`:''}</div></div>:detailError?<Empty><EmptyTitle>Incident unavailable</EmptyTitle><EmptyDescription>This record may have moved. Close this panel and search the archive.</EmptyDescription></Empty>:<Skeleton className="m-6 h-80"/>}</SheetContent></Sheet>
 </>;
}

export const dynamic = 'force-static';
