export type Incident = {
  id: string;
  legacy_id?: number;
  merged_ids?: string[];
  date: string;
  summary: string;
  location: string | null;
  location_group?: string | null;
  county: string | null;
  incident_type: string | null;
  outcome: string | null;
  victims: number | null;
  responding_agency: string | null;
  source_urls: string | null;
  notes?: string | null;
  peak?: string | null;
  place?: string | null;
  place_type?: string | null;
  setting?: string | null;
  detail_score?: string | number | null;
};
